name: Delete branch

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Delete branch
        run: |
          git push origin --delete 32-bit-test
          git push origin --delete 1437
          