name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: b4f1ba0
          fetch-depth: 0

      - name: Create branch
        run: |
          git switch -c release-0.2.1
          git push origin release-0.2.1