name: Delete branches

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Delete branches
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api --method DELETE \
            "/repos/${{ github.repository }}/git/refs/heads/zombatar-cleanroom-from-ResoddedFramework"